language: generic
matrix:
  include:
  - os: linux
    env:
    - JOB="Linux"
    dist: trusty
    script:
    - export SWIFT_VERSION=4.2.1
    - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
    - swift run -c release noise-tests
