name: benchmark

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    benchmark-macos:
        runs-on: macos-15
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Homebrew Mac
                if: ${{ runner.os == 'Macos' }}
                run: |
                    echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH
                    brew install jemalloc
            -   name: Ubuntu deps
                if: ${{ runner.os == 'Linux' }}
                run: |
                    sudo apt-get install -y libjemalloc-dev
            -   name: benchmark
                run: |
                    cd ExternalBenchmarks
                    swift package benchmark
